name: Create Release and Publish to PyPI
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish-to-pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup uv
        uses: astral-sh/setup-uv@v6.0.1
        with:
          enable-cache: true

      - name: Setup Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version-file: "pyproject.toml"

      - name: uv sync
        run: uv sync --all-extras --dev --locked

      - name: uv build
        run: uv build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: package-dist
          path: dist/

      - name: uv publish
        run: uv publish
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}

  create-release:
    runs-on: ubuntu-latest
    needs: publish-to-pypi

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4.3.0
        with:
          name: package-dist
          path: dist/

      - name: Generate Changelog
        run: |
          uv run \
            cz changelog \
              --file-name ${{ github.ref_name}}-CHANGELOG.md \
              ${{ github.ref_name }}

      - name: Create Release
        uses: softprops/action-gh-release@v2.2.2
        with:
          draft: true
          files: dist/*.{whl,tar.gz}
          body_path: ${{ github.ref_name}}-CHANGELOG.md
